### ISSUE TITLE
[Task]: Checklist for Updating/Writing Documentation for Bugomattic Launch

### ISSUE THREAD

**Issue by karenroldan** [Automattic/bugomattic#124]
### Details

We need to ensure that all relevant documentation is updated and any necessary new documents are created. 

Link to docs: https://docs.google.com/document/d/1y07S23smY63-Pj49yxTavAEy0pA9mSW2HtIcGDgcEDE/edit?usp=sharing

### Checklist

- [x] Write a heads-up post
- [x] Write an announcement post
- [x] Update Where to Report Issues in FG 
- [x] Update Where to Report Issues - Bugomattic in FG
- [ ] Update screenshot in How to Report Bugs 
- [x] Update [Bugomattic page](Pc4f5j-VO-p2) in WP.com Product Ambassadors

**Comment by karenroldan** [comment]
✅ Heads-up post: p7DVsv-hNk-p2
✅ Announcement post: pb6Nl-gEx-p2
✅ Where to Report Issues: Updated in FG
✅ Where to Report Issues - Bugomattic: Updated in FG
✅ Bugomattic in WP.com PA P2: Pc4f5j-VO-p2
